### ISSUE TITLE
ERROR: Attempt to index local 'popup'

### ISSUE THREAD

**Issue by madskjeldgaard** [RishabhRD/nvim-cheat.sh#2]
Hi I just installed this - and it works nicely. Very cool idea !!

But, the first time it opens a popup window, I get this:
```
E5108: Error executing lua ...share/nvim/plugged/nvim-cheat.sh/lua/nvim-cheat/init.lua:178: attempt to index local 'popup' (a boolean val
ue)  
```

(I do have popupfix installed)

**Comment by RishabhRD** [comment]
Hi! Thanks for the feedback. It should work fine now. Just update the popfix plugin. It was a popfix bug. I corrected that on my machine and forgot to push to master branch. So dumb of me :sweat_smile: Thanks for reporting this crucial thing!

**Comment by madskjeldgaard** [comment]
No problem and thanks so much for the response!

**Comment by madskjeldgaard** [comment]
It works great. Thanks!
