### ISSUE TITLE
Error: attempt to index local 'popup' (a boolean value)

### ISSUE THREAD

**Issue by Mongey** [RishabhRD/nvim-cheat.sh#3]
```vim
E5108: Error executing lua .../.vim/bundle/nvim-cheat.sh/lua/nvim-cheat/init.lua:178: attempt to index local 'popup' (a boolean value)
```

```
:version
NVIM v0.5.0-dev+973-gc64cce906
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by RishabhRD** [comment]
Hi! Thanks for the feedback. It should work fine now. Just update the popfix plugin. It was a popfix bug. I corrected that on my machine and forgot to push it to the master branch. So dumb of me :sweat_smile:  Thanks for reporting this crucial thing!
Hope it would fine now :)

**Comment by Mongey** [comment]
Thanks @RishabhRD that fixed it :)
